name: CICD

on: 
  push:
    branches:
    - main
    paths-ignore:
    - .gitignore
    - README.md

  pull_request:
    branches:
    - main
    paths-ignore:
    - .gitignore
    - README.md

jobs:
  run-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Build Here"

      - name: Test
        run: |
          echo "Test Here"

      - name: Deploy
        run: |
          echo "Deploy Here"

      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Release Here"
